# Generated by Django 4.2.1 on 2023-10-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created']},
        ),
    ]
