# Generated by Django 4.2.1 on 2023-10-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created']},
        ),
    ]
