# Generated by Django 4.2.1 on 2023-10-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0004_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['-created']},
        ),
    ]
