# Generated by Django 4.2.1 on 2023-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0005_alter_answers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='showAuthorName',
            field=models.BooleanField(default=False),
        ),
    ]
