# Generated by Django 4.2.1 on 2023-12-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HiddenHarbor', '0009_answers_likecount_question_likecount_likequs_likeans'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandUserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rand_userName', models.CharField(max_length=59)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HiddenHarbor.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
