# Generated by Django 4.2.1 on 2023-12-17 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HiddenHarbor', '0010_randusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
