# Generated by Django 4.2.1 on 2023-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Honor_score',
            field=models.IntegerField(default=0),
        ),
    ]
