# Generated by Django 4.2.1 on 2023-12-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0014_alter_profile_honor_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Honor_score',
            new_name='Honour_score',
        ),
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.IntegerField(default=0),
        ),
    ]
