# Generated by Django 4.2.1 on 2023-12-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiddenHarbor', '0015_rename_honor_score_profile_honour_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_image',
            field=models.CharField(max_length=200),
        ),
    ]
